use almoxarifado;

/*
SELECT ID, CATEGORIA_ID, NOME, QUANTIDADE_MINIMA
FROM ITEM_ESTOQUE 
WHERE QUANTIDADE_MINIMA >= 10 
ORDER BY  CATEGORIA_ID, QUANTIDADE_MINIMA DESC;
*/

/*
SELECT
	ITEM_ESTOQUE.ID,
	ITEM_ESTOQUE.CATEGORIA_ID,
    CATEGORIA.NOME AS CATEGORIA_NOME,
    CATEGORIA.DESCRICAO AS CATEGORIA_DESCRICAO,
    ITEM_ESTOQUE.NOME AS ITEM_NOME,
    ITEM_ESTOQUE.QUANTIDADE_MINIMA
FROM 
	ITEM_ESTOQUE
INNER JOIN 
	CATEGORIA ON ITEM_ESTOQUE.CATEGORIA_ID = CATEGORIA.ID
WHERE
	ITEM_ESTOQUE.QUANTIDADE_MINIMA > 10
ORDER BY 
	ITEM_ESTOQUE.CATEGORIA_ID, ITEM_ESTOQUE.NOME;
*/


SELECT
	ITEM_ESTOQUE.ID,
	ITEM_ESTOQUE.CATEGORIA_ID,
    LOCALIZACAO.NOME AS LOCALIZACAO_NOME,
    LOCALIZACAO.DESCRICAO AS LOCALIZACAO_DESCRICAO,
    CATEGORIA.NOME AS CATEGORIA_NOME,
    CATEGORIA.DESCRICAO AS CATEGORIA_DESCRICAO,
    ITEM_ESTOQUE.NOME AS ITEM_NOME,
    ITEM_ESTOQUE.QUANTIDADE_MINIMA
FROM 
	ITEM_ESTOQUE
INNER JOIN 
	CATEGORIA ON ITEM_ESTOQUE.CATEGORIA_ID = CATEGORIA.ID
INNER JOIN 
	LOCALIZACAO ON CATEGORIA.LOCALIZACAO_ID = LOCALIZACAO.ID
WHERE
	ITEM_ESTOQUE.QUANTIDADE_MINIMA > 10
ORDER BY 
	ITEM_ESTOQUE.CATEGORIA_ID, ITEM_ESTOQUE.NOME;