DROP DATABASE IF EXISTS DBLOJA;
CREATE DATABASE DBLOJA;
USE DBLOJA;

CREATE TABLE PRODUTO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    PRECO DECIMAL(10,2)
);

CREATE TABLE LOG (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    HORARIO TIMESTAMP,
    NOME_TABELA VARCHAR(100),
    ID_REGISTRO INT,
    DADO_ANTIGO VARCHAR(255),
    DADO_NOVO VARCHAR(255),
    CAMPO VARCHAR(50)
);

DELIMITER $$
CREATE PROCEDURE ADD_LOG(
    IN p_tabela VARCHAR(100),
    IN p_id INT,
    IN p_campo VARCHAR(50),
    IN p_valor_antigo VARCHAR(255),
    IN p_valor_novo VARCHAR(255)
)
BEGIN
    INSERT INTO LOG (HORARIO, NOME_TABELA, ID_REGISTRO, CAMPO, DADO_ANTIGO, DADO_NOVO)
    VALUES (CURRENT_TIMESTAMP(), p_tabela, p_id, p_campo, p_valor_antigo, p_valor_novo);
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRIGGER_LOG_PRODUTO
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN
   
    IF OLD.NOME <> NEW.NOME THEN
        CALL ADD_LOG('PRODUTO', OLD.ID, 'NOME', OLD.NOME, NEW.NOME);
    END IF;

    IF OLD.PRECO <> NEW.PRECO THEN
        CALL ADD_LOG('PRODUTO', OLD.ID, 'PRECO', OLD.PRECO, NEW.PRECO);
    END IF;

END $$
DELIMITER ;

INSERT INTO PRODUTO(NOME, PRECO) VALUES ('BANANA', 300);
INSERT INTO PRODUTO(NOME, PRECO) VALUES ('MACA', 20);

UPDATE PRODUTO SET NOME = 'MELAO', PRECO = 55 WHERE ID = 1;
UPDATE PRODUTO SET NOME = 'MELANCIA', PRECO = 87 WHERE ID = 2;

SELECT * FROM LOG;
SELECT * FROM PRODUTO;