CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE ALUNO(
	NOME VARCHAR(50),
    IDADE INT
);

INSERT INTO ALUNO(NOME, IDADE) VALUES ("Fulano", 17);
INSERT INTO ALUNO(NOME, IDADE) VALUES ("Ciclano", 16);
INSERT INTO ALUNO(NOME, IDADE) VALUES ("Beltrano", 16);
INSERT INTO ALUNO(NOME, IDADE) VALUES ("João", 16);
INSERT INTO ALUNO(NOME, IDADE) VALUES ("Pedro", 16);
INSERT INTO ALUNO(NOME, IDADE) VALUES ("Cléber", 16);
INSERT INTO ALUNO(NOME, IDADE) VALUES ("Jonas", 16);
INSERT INTO ALUNO(NOME, IDADE) VALUES ("Jamilton", 16);
INSERT INTO ALUNO(NOME, IDADE) VALUES ("Alexandre", 16);!