CREATE DATABASE ESTOQUE;
use estoque;

CREATE TABLE LOCALIZACAO (
    ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO TEXT
);

CREATE TABLE CATEGORIA_ITEM(
ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOCALIZACAO_ID INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO TEXT,
   
    FOREIGN KEY (LOCALIZACAO_ID) REFERENCES LOCALIZACAO(ID)
);

CREATE TABLE ITEM_ESTOQUE(
    ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA_ID INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO TEXT,
    QUANTIDADE_MINIMA INT NOT NULL DEFAULT 0,
    CODIGO VARCHAR(30) NOT NULL,
    NOME_IMAGEM VARCHAR(60)
)