DROP DATABASE IF EXISTS ESCOLA;
CREATE DATABASE ESCOLA;
USE ESCOLA;

CREATE TABLE AVALIACAO(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ALUNO VARCHAR(20),
    MATERIA VARCHAR(20),
    NOTA INT
);

INSERT INTO AVALIACAO
    (ALUNO, MATERIA, NOTA)
VALUES
    ('ALEXANDRE', 'BANCO DE DADOS', 10),
    ('ALEXANDRE', 'BANCO DE DADOS', 6),
    ('BRUNO', 'BANCO DE DADOS', 6),
    ('BRUNO', 'BANCO DE DADOS', 8),
   
    ('ALEXANDRE', 'FRONT END', 5),
    ('ALEXANDRE', 'FRONT END', 6),
    ('BRUNO', 'FRONT END', 5),
    ('BRUNO', 'FRONT END', 7);    