USE OFICINA;


-- Mostrando todos os trabalhos que estão sendo executados atualmente
SELECT 
    MECANICO.NOME AS MECANICO_NOME,
    VEICULO.PLACA AS VEICULO_PLACA,
    VEICULO.MODELO AS VEICULO_MODELO
FROM 
    MECANICO INNER JOIN VEICULO
    ON MECANICO.ID = VEICULO.MECANICO_ID;

-- Mostrando todos os veículos  
SELECT 
	VEICULO.MODELO AS VEIULO_MODELO,
    VEICULO.MARCA AS VEICULO_MARCA,
    MECANICO.NOME AS MECANICO_NOME
FROM
	VEICULO LEFT JOIN MECANICO
    ON VEICULO.MECANICO_ID = MECANICO.ID;
    
-- Mostrando todos os mecânicos
SELECT
	MECANICO.ID AS MECANICO_ID,
    MECANICO.NOME AS MECANICO_NOME,
    VEICULO.ID AS VEICULO_ID
FROM
	MECANICO LEFT JOIN VEICULO
    ON MECANICO.ID = VEICULO.MECANICO_ID;