CREATE DATABASE IF NOT EXISTS ESCOLA;

USE ESCOLA;

CREATE TABLE AVALIACAO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ALUNO VARCHAR(50),
    MATERIA VARCHAR(50),
    NOTA INT
);

INSERT INTO AVALIACAO(ALUNO, MATERIA, NOTA)
VALUES
('ALEXANDRE', 'BANCO DE DADOS', 10),
('ALEXANDRE', 'BANCO DE DADOS', 6),
('BRUNO', 'BANCO DE DADOS', 6),
('BRUNO', 'BANCO DE DADOS', 8),
('ALEXANDRE', 'FRONT END', 5),
('ALEXANDRE', 'FRONT END', 6),
('BRUNO', 'FRONT END', 5),
('BRUNO', 'FRONT END', 7);

#MÉDIA DA SALA
SELECT
    AVG(NOTA) AS MEDIA_SALA
FROM
    AVALIACAO;

#MÉDIA POR ALUNO
SELECT
    ALUNO,
    AVG(NOTA) AS MEDIA_ALUNO,
    SUM(NOTA) AS SOMA_NOTAS
FROM
    AVALIACAO
GROUP BY
    ALUNO;

#MÉDIA POR MATÉRIA
SELECT
    MATERIA,
    AVG(NOTA) AS MEDIA_MATERIA
FROM
    AVALIACAO
GROUP BY
    MATERIA;

#MÉDIA POR ALUNO E MATÉRIA
SELECT
    MATERIA,
    ALUNO,
    AVG(NOTA) AS MEDIA_ALUNO,
    SUM(NOTA) AS SOMA_NOTAS,
    CASE 
        WHEN AVG(NOTA) >= 7 THEN "APROVADO"
        ELSE "REPROVADO"
    END AS SITUACAO
FROM
    AVALIACAO
GROUP BY
    MATERIA,
    ALUNO;