CREATE DATABASE VETERINARIA;

USE VETERINARIA;

CREATE TABLE PET(
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50),
    IDADE INT,
    RACA VARCHAR(20),
    DESCRICAO TEXT,

    PRIMARY KEY(ID)
);