use estoque;

/*
ALTER TABLE LOCALIZACAO
ADD COLUMN AREA_M2 NUMERIC(8, 2);
*/

/*
INSERT INTO LOCALIZACAO(NOME, DESCRICAO, AREA_M2) 
VALUES ("BLOCO X", "BLA BLA BLA", 10.5);
*/

/*
ALTER TABLE LOCALIZACAO
ADD COLUMN COR VARCHAR(20) NOT NULL;
*/

/*
ALTER TABLE LOCALIZACAO
MODIFY COLUMN COR VARCHAR(20) NOT NULL DEFAULT "ROSA";
*/

/*
INSERT INTO LOCALIZACAO(NOME, DESCRICAO, AREA_M2) 
VALUES ("BLOCO Y", "BLA BLA", 9.21);
*/

/*
ALTER TABLE LOCALIZACAO 
DROP COLUMN AREA_M2;
*/

/*
ALTER TABLE LOCALIZACAO
RENAME COLUMN COR TO COLORACAO;
*/

/*
INSERT INTO LOCALIZACAO(NOME, DESCRICAO, COLORACAO) 
VALUES ("BLOCO Y", "BLA BLA", "VERDE");
*/

-- ALTER TABLE CATEGORIA_ITEM DROP FOREIGN KEY CATEGORIA_ITEM_IBFK_1;

-- DROP TABLE LOCALIZACAO;