DROP DATABASE IF EXISTS BANCO_TESTE2;

CREATE DATABASE BANCO_TESTE2;

USE BANCO_TESTE2;

CREATE TABLE PESSOA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    DATA_NASCIMENTO DATE
);

SET GLOBAL log_bin_trust_function_creators = 1;

DELIMITER $$
CREATE FUNCTION CALCULAR_IDADE(P_DATA_NASCIMENTO DATE)
RETURNS INT NOT DETERMINISTIC
BEGIN
    DECLARE IDADE INT;
    SET IDADE = TIMESTAMPDIFF(YEAR, P_DATA_NASCIMENTO, CURDATE());
    RETURN IDADE;
END $$
DELIMITER;

INSERT INTO PESSOA (NOME, DATA_NASCIMENTO) VALUES ('Roberto', '2007-05-15');

SELECT 
    NOME,
    DATA_NASCIMENTO,
    CALCULAR_IDADE(DATA_NASCIMENTO) AS IDADE
FROM PESSOA;