-- CREATE DATABASE ESCOLA;

-- USE ESCOLA;

/*
CREATE TABLE ALUNO(
	ID_ALUNO INT PRIMARY KEY,
	NOME VARCHAR(255)
);
*/

/*
CREATE TABLE AULA(
	ID_AULA INT PRIMARY KEY,
	HORA_INICIO DATETIME,
    HORA_FIM DATETIME
);
*/

/*
CREATE TABLE FREQUENCIA(
	ID_AULA INT,
    ID_ALUNO INT,
    PRIMARY KEY (ID_AULA, ID_ALUNO),
    FOREIGN KEY (ID_AULA) REFERENCES AULA(ID_AULA),
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID_ALUNO)
);
*/
