CREATE DATABASE ESTOQUE;

USE ESTOQUE;

CREATE TABLE LOCALIZACAO (
    ID INT AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO TEXT,
    
    PRIMARY KEY(ID)
);
	
CREATE TABLE CATEGORIA_ITEM(
    ID INT AUTO_INCREMENT NOT NULL,
    LOCALIZACAO_ID INT,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO TEXT,
    
	PRIMARY KEY(ID),
   
    FOREIGN KEY (LOCALIZACAO_ID) REFERENCES LOCALIZACAO(ID)
);

CREATE TABLE ITEM_ESTOQUE(
	ID INT AUTO_INCREMENT NOT NULL,
	CATEGORIA_ID INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DESCRICAO TEXT,
	QUANTIDADE_MINIMA INT NOT NULL DEFAULT 0,
	CODIGO VARCHAR(30) NOT NULL,
	NOME_IMAGEM VARCHAR(60),

	PRIMARY KEY(ID),

	FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA_ITEM(ID)
);

INSERT INTO LOCALIZACAO (NOME, DESCRICAO) 
VALUES ("GALPÃO A", "...");

INSERT INTO LOCALIZACAO (NOME, DESCRICAO) 
VALUES ("TENDA B", "...");

INSERT INTO LOCALIZACAO (NOME, DESCRICAO) 
VALUES ("PRÉDIO C", "...");

INSERT INTO CATEGORIA_ITEM (LOCALIZACAO_ID, NOME, DESCRICAO) 
VALUES (1, "METAIS", "...");

INSERT INTO CATEGORIA_ITEM (LOCALIZACAO_ID, NOME, DESCRICAO) 
VALUES (2, "INFLAMÁVEIS", "...");

INSERT INTO CATEGORIA_ITEM (LOCALIZACAO_ID, NOME, DESCRICAO) 
VALUES (3, "ALIMENTOS", "...");

INSERT INTO ITEM_ESTOQUE (CATEGORIA_ID, NOME, DESCRICAO, QUANTIDADE_MINIMA, CODIGO, NOME_IMAGEM)
VALUES (1, "CHAPA DE AÇO", "...", 50, "WEFG", "CHAPA_ACO.PNG");

INSERT INTO ITEM_ESTOQUE (CATEGORIA_ID, NOME, DESCRICAO, QUANTIDADE_MINIMA, CODIGO, NOME_IMAGEM)
VALUES (2, "BOTIJÃO DE GÁS", "...", 100, "NILV", "BOTIJAO.PNG");

INSERT INTO ITEM_ESTOQUE (CATEGORIA_ID, NOME, DESCRICAO, QUANTIDADE_MINIMA, CODIGO, NOME_IMAGEM)
VALUES (3, "PRESUNTO", "...", 200, "FHDM", "PRESUNTO.PNG");

UPDATE CATEGORIA_ITEM
SET NOME = "FRIOS"
WHERE ID = 3;

DELETE FROM ITEM_ESTOQUE
WHERE ID = 3;