DROP DATABASE IF EXISTS LOJA;

CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTOS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    PRECO_VENDA DECIMAL(8, 2)
);

CREATE TABLE SAIDA_PRODUTOS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(50) NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL DEFAULT 0,
    
    FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID)
);

INSERT INTO PRODUTOS (NOME, PRECO_VENDA) 
VALUES 
("PÃO FRANCÊS", 0.20),
("QUEIJO MINAS", 15),
("CAFÉ 500g", 25);

INSERT INTO SAIDA_PRODUTOS (ID_PRODUTO, DESCRICAO, QUANTIDADE)
VALUES
(1, "VENDA", 3),
(1, "VENDA", 7),
(1, "VENDA", 15),
(1, "VENDA", 5),
(1, "VENDA", 4),
(2, "VENDA", 2),
(2, "VENDA", 5),
(2, "VENDA", 1),
(2, "VENDA", 3),
(2, "VENDA", 2),
(3, "VENDA", 2),
(3, "VENDA", 3),
(3, "VENDA", 5),
(3, "VENDA", 2),
(3, "VENDA", 1);

#SOMA E MÉDIA DE VENDAS DE TODAS AS VENDAS
SELECT
    ROUND(AVG(SP.QUANTIDADE), 2) AS MEDIA_VENDA,
    SUM(SP.QUANTIDADE) AS SOMA_VENDA
FROM
	PRODUTOS AS PROD INNER JOIN SAIDA_PRODUTOS SP ON PROD.ID = SP.ID_PRODUTO;
    
#SOMA DE VENDAS POR PRODUTO
SELECT
	PROD.NOME AS NOME_PRODUTO,
    SUM(SP.QUANTIDADE) AS SOMA_VENDA
FROM
	PRODUTOS AS PROD INNER JOIN SAIDA_PRODUTOS SP ON PROD.ID = SP.ID_PRODUTO
GROUP BY
	PROD.NOME;
    
#MÉDIA DE VALORES DE VENDA POR PRODUTO
SELECT
	PROD.NOME AS NOME_PRODUTO,
    ROUND(AVG(SP.QUANTIDADE * PROD.PRECO_VENDA), 2) AS MEDIA_VALOR
FROM
	PRODUTOS AS PROD INNER JOIN SAIDA_PRODUTOS SP ON PROD.ID = SP.ID_PRODUTO
GROUP BY
	PROD.NOME;