DROP DATABASE IF EXISTS MERCADO;

CREATE DATABASE MERCADO;

USE MERCADO;

CREATE TABLE CAIXA(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE_VENDIDA INT NOT NULL,
    DATA_MOVIMENTACAO DATETIME NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL
);

CREATE TABLE PRODUTOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    QUANTIDADE INT NOT NULL,
    PRECO DECIMAL(8, 2) NOT NULL
);

INSERT INTO PRODUTOS (NOME, DESCRICAO, QUANTIDADE, PRECO)
VALUES
    ("Arroz", "Pacote de arroz 5kg", 200, 25.50),
    ("Feijão", "Pacote de feijão 1kg", 500, 15.99),
    ("Frango", "Filé de peito 1kg", 300, 19.99),
    ("Picanha", "Picanha bovina 1,5kg", 150, 85.50),
    ("Farofa", "Farofa com limão 500g", 250, 22.00)

INSERT INTO CAIXA (ID_PRODUTO, QUANTIDADE_VENDIDA, DATA_MOVIMENTACAO, VALOR)
VALUES
    (1, 40, "2025-07-10", 1020),
    (3, 20, "2025-07-12", 399.8),
    (4, 10, "2025-07-15", 855)