#DELETA O BANCO DE DADOS "ESTOQUE" SE ELE EXISTIR
DROP DATABASE IF EXISTS ESTOQUE;

#CRIA O BANCO DE DADOS "ESTOQUE"
CREATE DATABASE ESTOQUE;

#DIRECIONA OS PRÓXIMOS COMANDOS PARA O BANCO "ESTOQUE"
USE ESTOQUE;

CREATE TABLE MATERIAL(
	ID INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(50)
);

CREATE TABLE ENTRADA_MATERIAL(
	ID INT NOT NULL PRIMARY KEY,
    MOTIVO VARCHAR(50) NOT NULL,
    QUANTIDADE INT NOT NULL DEFAULT 1,
    ID_MATERIAL INT NOT NULL,
    
    FOREIGN KEY(ID_MATERIAL) REFERENCES MATERIAL(ID)
);

CREATE TABLE SAIDA_MATERIAL(
	ID INT NOT NULL PRIMARY KEY,
    MOTIVO VARCHAR(50) NOT NULL,
    QUANTIDADE INT NOT NULL DEFAULT 1,
    ID_MATERIAL INT NOT NULL,
    
    FOREIGN KEY(ID_MATERIAL) REFERENCES MATERIAL(ID)
);

INSERT INTO MATERIAL VALUES 
	(1, 'ESCUDO'),
    (2, 'ESPADA'),
    (3, 'ALABARDA'),
    (4, 'MAÇA');
 
INSERT INTO ENTRADA_MATERIAL
	(ID, MOTIVO, QUANTIDADE, ID_MATERIAL)
VALUES 
	(1, 'COMPRA', 5, 1),
    (2, 'COMPRA', 10, 2);
    
INSERT INTO SAIDA_MATERIAL
	(ID, MOTIVO, QUANTIDADE, ID_MATERIAL)
VALUES
	(1, 'SUBSTITUIÇÃO POR QUEBRA', 1, 1);
        
SELECT
	MAT.ID AS ID_DO_MATERIAL,
    MAT.NOME AS NOME_DO_MATERIAL,
	SUM(COALESCE(EM.QUANTIDADE, 0)) AS ENTRADAS, #SOMA AS QUANTIDADES DA TABELA ENTRADA
    SUM(COALESCE(SM.QUANTIDADE, 0)) AS SAIDAS, # SOMA AS QUANTIDADES DA TABELA SAIDA
    SUM(COALESCE(EM.QUANTIDADE, 0)) - SUM(COALESCE(SM.QUANTIDADE, 0)) AS SALDO #CALCULA A DIFERENÇA ENTRE AS SOMAS DAS TABELAS ENTRADA E SAIDA
FROM 
	MATERIAL MAT 
    LEFT JOIN ENTRADA_MATERIAL EM ON MAT.ID = EM.ID_MATERIAL # JUNTA A TABELA DE ENTRADA COM A TABELA DE MATERIAL
    LEFT JOIN SAIDA_MATERIAL SM ON MAT.ID = SM.ID_MATERIAL # JUNTA A TABELA DE SAÍDA COM A TABELA DE MATERIAL
GROUP BY
	MAT.ID, MAT.NOME # AGRUPA O RESULTADO DA CONSULTA POR ID E NOME DO MATERIAL




    
