CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE CURSOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(80) NOT NULL,
    DESCRICAO TEXT,
    PRECO DECIMAL(8, 2) NOT NULL,
	CARGA_HORARIA INT NOT NULL
);