DROP DATABASE IF EXISTS BIBLIOTECA;

CREATE DATABASE BIBLIOTECA;

USE BIBLIOTECA;

CREATE TABLE LIVROS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    GENERO VARCHAR(50)
);

DELIMITER $$
CREATE PROCEDURE SALVAR_LIVRO(
    IN PID INT,
    IN PNOME VARCHAR(50),
    IN PGENERO VARCHAR(50)
)
BEGIN
    IF (COALESCE(PID, 0) > 0) THEN
        UPDATE LIVROS SET NOME = PNOME, GENERO = PGENERO WHERE ID = PID;
    ELSE
        INSERT INTO LIVROS (NOME, GENERO) VALUES (PNOME, PGENERO);
    END IF;
END$$
DELIMITER ;

CALL SALVAR_LIVRO(NULL, "CHAPEUZINHO VERMELHO", "CONTO DE FADA");
CALL SALVAR_LIVRO(1, "O LABIRINTO DO FAUNO", "AVENTURA");