DROP DATABASE IF EXISTS COOKIE_DB;

CREATE DATABASE COOKIE_DB;

USE COOKIE_DB;

CREATE TABLE USUARIOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL
);

INSERT INTO USUARIOS (NOME, SENHA) VALUES 
('alexandre', '1234'),
('bruno', '5678');
