DROP DATABASE IF EXISTS POKEDEX; 
CREATE DATABASE POKEDEX; 

USE POKEDEX;

CREATE TABLE POKEMON(
	ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    DESCRICAO TEXT,
    FOTO VARCHAR(30),   
    PRIMARY KEY(ID)
);

