-- CREATE DATABASE DBRH;

USE DBRH;

/*
CREATE TABLE FUNCIONARIO(
	ID INT AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(100),
    DATA_NASCIMENTO DATE,

	PRIMARY KEY(ID)
);
*/

-- INSERT INTO FUNCIONARIO(ID, NOME, DATA_NASCIMENTO) VALUES (1, "JOÃO", "2000-10-02");

-- INSERT INTO FUNCIONARIO(NOME, DATA_NASCIMENTO) VALUES ("JOSÉ", "2001-10-02");

-- INSERT INTO FUNCIONARIO(ID, NOME, DATA_NASCIMENTO) VALUES (4, "CARLA", "2000-10-02");

-- INSERT INTO FUNCIONARIO(ID, NOME, DATA_NASCIMENTO) VALUES (5, "MARIA", "2000-10-02");

-- INSERT INTO FUNCIONARIO(NOME, DATA_NASCIMENTO) VALUES ("MARCELO", "2001-09-02");

-- INSERT INTO FUNCIONARIO(NOME, DATA_NASCIMENTO) VALUES ("FÁTIMA", "2000-08-02");

/*
UPDATE FUNCIONARIO
SET NOME = "PEDRO"
WHERE ID = 2;
*/

/*
UPDATE FUNCIONARIO
SET DATA_NASCIMENTO = "1999-10-10"
WHERE ID >= 6;
*/

/*
DELETE FROM FUNCIONARIO
WHERE ID = 7;
*/

SELECT * FROM FUNCIONARIO;


