CREATE DATABASE POKEDEX;

USE POKEDEX;

CREATE TABLE POKEMON(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    NOME_IMAGEM VARCHAR(50) NOT NULL
);