CREATE DATABASE IF NOT EXISTS ESTOQUE;

USE ESTOQUE;

CREATE TABLE MATERIAL(
    ID INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50)
);

CREATE TABLE ENTRADA_MATERIAL(
    ID INT NOT NULL PRIMARY KEY,
    ID_MATERIAL INT NOT NULL,
    MOTIVO VARCHAR(50) NOT NULL,
    QUANTIDADE INT NOT NULL DEFAULT 1,

    FOREIGN KEY(ID_MATERIAL) REFERENCES MATERIAL(ID)
);

CREATE TABLE SAIDA_MATERIAL(
    ID INT NOT NULL PRIMARY KEY,
    ID_MATERIAL INT NOT NULL,
    MOTIVO VARCHAR(50) NOT NULL,
    QUANTIDADE INT NOT NULL DEFAULT 1,

    FOREIGN KEY(ID_MATERIAL) REFERENCES MATERIAL(ID)
);

/*
CREATE TABLE MOVIMENTACAO_MATERIAL(
    ID INT NOT NULL PRIMARY KEY,
    ID_MATERIAL INT NOT NULL,
    MOTIVO VARCHAR(50) NOT NULL,
    QUANTIDADE INT NOT NULL DEFAULT 1,
    ENTRADA_SAIDA CHAR(1) NOT NULL DEFAULT 'E',

    FOREIGN KEY(ID_MATERIAL) REFERENCES MATERIAL(ID)
);

INSERT INTO MATERIAL (ID, NOME)
VALUES(1, "ESPADA");

INSERT INTO MATERIAL (ID, NOME)
VALUES(2, "ESCUDO");

INSERT INTO MATERIAL (ID, NOME)
VALUES(3, "MACHADO");

INSERT INTO MATERIAL (ID, NOME)
VALUES(4, "ALABARDA");

INSERT INTO MOVIMENTACAO_MATERIAL(ID, ID_MATERIAL, MOTIVO, QUANTIDADE, ENTRADA_SAIDA)
VALUES  
(1, 1, "COMPRA", 10, "E"),
(2, 3, "SUBSTITUIÇÃO", 1, "S"),
(3, 4, "COMPRA", 50, "E");

SELECT
    MOVIMENTACAO_MATERIAL.ID,
    MATERIAL.NOME AS MATERIAL_NOME,
    MOVIMENTACAO_MATERIAL.MOTIVO,
    MOVIMENTACAO_MATERIAL.QUANTIDADE,
    MOVIMENTACAO_MATERIAL.ID_MATERIAL,
    MOVIMENTACAO_MATERIAL.ENTRADA_SAIDA
FROM 
    MOVIMENTACAO_MATERIAL INNER JOIN MATERIAL
ON MOVIMENTACAO_MATERIAL.ID_MATERIAL = MATERIAL.ID;

SELECT
(SELECT SUM(QUANTIDADE) FROM MOVIMENTACAO_MATERIAL WHERE ENTRADA_SAIDA = "E") - 
(SELECT SUM(QUANTIDADE) FROM MOVIMENTACAO_MATERIAL WHERE ENTRADA_SAIDA = "S")
AS SALDO;
*/

INSERT INTO MATERIAL (ID, NOME)
VALUES
(1, "ESPADA"),
(2, "ESCUDO"),
(3, "MACHADO"),
(4, "ALABARDA");

INSERT INTO ENTRADA_MATERIAL(ID, ID_MATERIAL, MOTIVO, QUANTIDADE)
VALUES
(1, 1, "COMPRA", 10),
(2, 2, "COMPRA", 15),
(3, 3, "COMPRA", 25),
(4, 4, "COMPRA", 50);

INSERT INTO SAIDA_MATERIAL(ID, ID_MATERIAL, MOTIVO, QUANTIDADE)
VALUES  
(2, 3, "SUBSTITUIÇÃO POR QUEBRA", 1),
(3, 1, "SUBSTITUIÇÃO POR QUEBRA", 4),
(4, 2, "SUBSTITUIÇÃO POR QUEBRA", 7),
(5, 4, "SUBSTITUIÇÃO POR QUEBRA", 10);

SELECT
    MAT.NOME AS NOME_MATERIAL,
    SUM(COALESCE(EM.QUANTIDADE, 0)) AS ENTRADAS,
    SUM(COALESCE(SM.QUANTIDADE, 0)) AS SAIDAS,
    (SUM(COALESCE(EM.QUANTIDADE, 0)) - SUM(COALESCE(SM.QUANTIDADE, 0))) AS SALDO
FROM 
    MATERIAL MAT 
    LEFT JOIN ENTRADA_MATERIAL EM ON MAT.ID = EM.ID_MATERIAL
    LEFT JOIN SAIDA_MATERIAL SM ON MAT.ID = SM.ID_MATERIAL
GROUP BY
    MAT.NOME;